# Generated by Django 5.2.17 on 2026-09-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0004_prices"),
        ("planning", "0008_tourstop_notice_wanted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="wann"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("plan", "Fahrplan"),
                            ("notice", "Aushang"),
                            ("order", "Montageauftrag"),
                            ("status", "Status"),
                            ("note", "Notiz"),
                            ("documents", "Unterlagen"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Bereich",
                    ),
                ),
                ("text", models.CharField(max_length=400, verbose_name="was")),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="buildings.building",
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="buildings.installationorder",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="planning.tour",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="wer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verlauf-Eintrag",
                "verbose_name_plural": "Verlauf",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("info", "Hinweis"),
                            ("storno", "Storno"),
                            ("wish", "Terminwunsch"),
                            ("access", "Zugang / Schlüssel"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="Notiz")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="geschrieben am"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="erledigt am"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="von",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="buildings.installationorder",
                        verbose_name="Montageauftrag",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="erledigt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notiz",
                "verbose_name_plural": "Notizen",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("building__isnull", False),
                            ("installation_order__isnull", False),
                            _connector="OR",
                        ),
                        name="note_has_target",
                    )
                ],
            },
        ),
    ]
