# Generated by Django 5.2.17 on 2026-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("plan", "Fahrplan"),
                    ("notice", "Aushang"),
                    ("order", "Montageauftrag"),
                    ("status", "Status"),
                    ("note", "Notiz"),
                    ("documents", "Unterlagen"),
                    ("field", "vor Ort"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Bereich",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="kind",
            field=models.CharField(
                choices=[
                    ("info", "Hinweis"),
                    ("storno", "Storno"),
                    ("wish", "Terminwunsch"),
                    ("access", "Zugang / Schlüssel"),
                    ("problem", "Problem vor Ort"),
                ],
                default="info",
                max_length=20,
                verbose_name="Art",
            ),
        ),
    ]
