# Generated by Django 5.2.17 on 2026-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_field_kinds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("plan", "Fahrplan"),
                    ("notice", "Aushang"),
                    ("order", "Montageauftrag"),
                    ("status", "Status"),
                    ("note", "Notiz"),
                    ("documents", "Unterlagen"),
                    ("office", "Bearbeitung"),
                    ("field", "vor Ort"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Bereich",
            ),
        ),
    ]
