# Generated by Django 5.2.17 on 2026-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autoplan",
                    models.BooleanField(
                        default=False,
                        help_text="Eingefroren – soll später weiterentwickelt werden. Eingeschaltet erscheint im Kalender der Knopf „Automatisch planen“: das System verteilt ungeplante Stopps auf freie Tage (Vorschlag, erst nach Bestätigung gespeichert).",
                        verbose_name="🤖 Automatisch planen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funktionen",
                "verbose_name_plural": "Funktionen",
            },
        ),
    ]
