# Generated by Django 5.2.17 on 2026-09-29 13:18

from django.db import migrations, models


def mein_tag_not_for_disposition(apps, schema_editor):
    """📱 Mein Tag is for Ableser/Monteur (and Admin); the Disposition had it by default before."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    group = Group.objects.filter(name="Disposition").first()
    if group:
        group.permissions.remove(*Permission.objects.filter(
            content_type__app_label="planning", codename__in=["view_own_tours", "mark_stop_done"]))


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=80, verbose_name="Rolle")),
                ("permission", models.CharField(max_length=150, verbose_name="Recht")),
            ],
            options={
                "verbose_name": "Standardrecht (vergeben)",
                "verbose_name_plural": "Standardrechte (vergeben)",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.RunPython(mein_tag_not_for_disposition, migrations.RunPython.noop),
    ]
