# Generated by Django 5.2.17 on 2026-09-26 17:25

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Breitengrad"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "noch nicht gesucht"),
                            ("ok", "gefunden"),
                            ("failed", "nicht gefunden"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Geocoding",
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geocodiert am"
                    ),
                ),
                (
                    "geocoded_address",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="geocodierte Adresse"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Kurzname"
                    ),
                ),
                ("can_read", models.BooleanField(default=True, verbose_name="Ableser")),
                (
                    "can_install",
                    models.BooleanField(default=False, verbose_name="Monteur"),
                ),
                (
                    "calendar_color",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="Kalenderfarbe"
                    ),
                ),
                (
                    "max_daily_minutes",
                    models.PositiveSmallIntegerField(
                        default=450, verbose_name="max. Netto-Arbeitszeit/Tag (min)"
                    ),
                ),
                (
                    "default_start_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="übliche Startzeit"
                    ),
                ),
                (
                    "work_window_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Zeitfenster von"
                    ),
                ),
                (
                    "work_window_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Zeitfenster bis"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
                "ordering": ["short_name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAbsence",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Urlaub"),
                            ("sick", "Krank"),
                            ("training", "Schulung"),
                            ("other", "Sonstiges"),
                        ],
                        default="vacation",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="von")),
                ("end_date", models.DateField(verbose_name="bis")),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="Notiz"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planning.employee",
                        verbose_name="Mitarbeiter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Abwesenheit",
                "verbose_name_plural": "historical Abwesenheiten",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Breitengrad"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "noch nicht gesucht"),
                            ("ok", "gefunden"),
                            ("failed", "nicht gefunden"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Geocoding",
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geocodiert am"
                    ),
                ),
                (
                    "geocoded_address",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="geocodierte Adresse"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Kurzname"
                    ),
                ),
                ("can_read", models.BooleanField(default=True, verbose_name="Ableser")),
                (
                    "can_install",
                    models.BooleanField(default=False, verbose_name="Monteur"),
                ),
                (
                    "calendar_color",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="Kalenderfarbe"
                    ),
                ),
                (
                    "max_daily_minutes",
                    models.PositiveSmallIntegerField(
                        default=450, verbose_name="max. Netto-Arbeitszeit/Tag (min)"
                    ),
                ),
                (
                    "default_start_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="übliche Startzeit"
                    ),
                ),
                (
                    "work_window_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Zeitfenster von"
                    ),
                ),
                (
                    "work_window_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Zeitfenster bis"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="aktiv")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Mitarbeiter",
                "verbose_name_plural": "historical Mitarbeiter",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTour",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Datum")),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="Beginn"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "vorläufig"),
                            ("confirmed", "bestätigt"),
                            ("done", "erledigt"),
                        ],
                        default="provisional",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "needs_recalculation",
                    models.BooleanField(default=False, verbose_name="neu rechnen"),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Änderungsgrund"
                    ),
                ),
                (
                    "routing_source",
                    models.CharField(
                        choices=[
                            ("none", "keine echten Fahrzeiten"),
                            ("tomtom", "TomTom"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Fahrzeiten",
                    ),
                ),
                (
                    "routing_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Quelle der Fahrzeiten"
                    ),
                ),
                (
                    "routing_calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fahrzeiten gerechnet am"
                    ),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ablese-/Montagezeit (min)"
                    ),
                ),
                (
                    "drive_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fahrzeit (min)"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=7,
                        verbose_name="Strecke (km)",
                    ),
                ),
                (
                    "break_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Pause (min)"),
                ),
                (
                    "break_after_position",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pause nach Stopp"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                (
                    "commute_to_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Anfahrt von zu Hause (min)"
                    ),
                ),
                (
                    "commute_to_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Anfahrt (km)",
                    ),
                ),
                (
                    "commute_from_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Heimfahrt (min)"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bestätigt am"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bestätigt von",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planning.employee",
                        verbose_name="Mitarbeiter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fahrplan",
                "verbose_name_plural": "historical Fahrpläne",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Datum")),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="Beginn"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "vorläufig"),
                            ("confirmed", "bestätigt"),
                            ("done", "erledigt"),
                        ],
                        default="provisional",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                (
                    "needs_recalculation",
                    models.BooleanField(default=False, verbose_name="neu rechnen"),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Änderungsgrund"
                    ),
                ),
                (
                    "routing_source",
                    models.CharField(
                        choices=[
                            ("none", "keine echten Fahrzeiten"),
                            ("tomtom", "TomTom"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Fahrzeiten",
                    ),
                ),
                (
                    "routing_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Quelle der Fahrzeiten"
                    ),
                ),
                (
                    "routing_calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fahrzeiten gerechnet am"
                    ),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ablese-/Montagezeit (min)"
                    ),
                ),
                (
                    "drive_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fahrzeit (min)"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=7,
                        verbose_name="Strecke (km)",
                    ),
                ),
                (
                    "break_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Pause (min)"),
                ),
                (
                    "break_after_position",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pause nach Stopp"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="Ende"),
                ),
                (
                    "commute_to_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Anfahrt von zu Hause (min)"
                    ),
                ),
                (
                    "commute_to_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Anfahrt (km)",
                    ),
                ),
                (
                    "commute_from_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Heimfahrt (min)"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="bestätigt am"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bestätigt von",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tours",
                        to="planning.employee",
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fahrplan",
                "verbose_name_plural": "Fahrpläne",
                "ordering": ["date", "employee__short_name"],
                "permissions": [
                    ("confirm_tour", "Fahrplan bestätigen"),
                    ("view_own_tours", "Eigenen Tagesplan sehen"),
                    ("view_reports", "Auswertungen und Zeiten je Ableser sehen"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTourStop",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(verbose_name="Reihenfolge"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("reading", "Ablesung"), ("installation", "Montage")],
                        default="reading",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "is_fixed",
                    models.BooleanField(default=False, verbose_name="Fixtermin"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="von"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="bis"),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Dauer (min)"),
                ),
                (
                    "drive_to_next_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fahrt exakt (s)"
                    ),
                ),
                (
                    "drive_to_next_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fahrt im Plan (min)"
                    ),
                ),
                (
                    "drive_to_next_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Fahrt (km)",
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(blank=True, null=True, verbose_name="Abfahrt"),
                ),
                (
                    "drive_source",
                    models.CharField(
                        choices=[
                            ("none", "keine"),
                            ("estimate", "Schätzung"),
                            ("tomtom", "TomTom"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Fahrzeit-Quelle",
                    ),
                ),
                (
                    "route_warnings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Hinweise zur Strecke"
                    ),
                ),
                (
                    "field_note",
                    models.TextField(blank=True, verbose_name="Notiz vor Ort"),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="erledigt am"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="erledigt von",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="buildings.installationorder",
                        verbose_name="Montageauftrag",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planning.tour",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stopp",
                "verbose_name_plural": "historical Stopps",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TourStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(verbose_name="Reihenfolge"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("reading", "Ablesung"), ("installation", "Montage")],
                        default="reading",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "is_fixed",
                    models.BooleanField(default=False, verbose_name="Fixtermin"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="von"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="bis"),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Dauer (min)"),
                ),
                (
                    "drive_to_next_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fahrt exakt (s)"
                    ),
                ),
                (
                    "drive_to_next_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fahrt im Plan (min)"
                    ),
                ),
                (
                    "drive_to_next_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Fahrt (km)",
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(blank=True, null=True, verbose_name="Abfahrt"),
                ),
                (
                    "drive_source",
                    models.CharField(
                        choices=[
                            ("none", "keine"),
                            ("estimate", "Schätzung"),
                            ("tomtom", "TomTom"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Fahrzeit-Quelle",
                    ),
                ),
                (
                    "route_warnings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Hinweise zur Strecke"
                    ),
                ),
                (
                    "field_note",
                    models.TextField(blank=True, verbose_name="Notiz vor Ort"),
                ),
                (
                    "done_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="erledigt am"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tour_stops",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="erledigt von",
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tour_stops",
                        to="buildings.installationorder",
                        verbose_name="Montageauftrag",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="planning.tour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stopp",
                "verbose_name_plural": "Stopps",
                "ordering": ["tour", "position"],
                "permissions": [
                    ("mark_stop_done", "Stopp als erledigt markieren"),
                    ("add_field_note", "Notiz vor Ort erfassen"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("vacation", "Urlaub"),
                            ("sick", "Krank"),
                            ("training", "Schulung"),
                            ("other", "Sonstiges"),
                        ],
                        default="vacation",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="von")),
                ("end_date", models.DateField(verbose_name="bis")),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="Notiz"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="planning.employee",
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abwesenheit",
                "verbose_name_plural": "Abwesenheiten",
                "ordering": ["start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="absence_end_after_start",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tour",
            constraint=models.UniqueConstraint(
                fields=("employee", "date"), name="one_tour_per_employee_and_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="tourstop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building__isnull", False),
                        ("installation_order__isnull", True),
                        ("kind", "reading"),
                    ),
                    models.Q(
                        ("installation_order__isnull", False), ("kind", "installation")
                    ),
                    _connector="OR",
                ),
                name="stop_kind_matches_reference",
            ),
        ),
    ]
