# Generated by Django 5.2.17 on 2026-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="geocode_status",
            field=models.CharField(
                choices=[
                    ("pending", "noch nicht gesucht"),
                    ("ok", "gefunden"),
                    ("approximate", "ungefähr (ohne Hausnummer)"),
                    ("failed", "nicht gefunden"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Geocoding",
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployee",
            name="geocode_status",
            field=models.CharField(
                choices=[
                    ("pending", "noch nicht gesucht"),
                    ("ok", "gefunden"),
                    ("approximate", "ungefähr (ohne Hausnummer)"),
                    ("failed", "nicht gefunden"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Geocoding",
            ),
        ),
    ]
