# Generated by Django 5.2.17 on 2026-09-29 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_employee_geocode_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltour",
            name="time_approval_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Begründung Arbeitszeit"
            ),
        ),
        migrations.AddField(
            model_name="historicaltour",
            name="time_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Arbeitszeit übernommen am"
            ),
        ),
        migrations.AddField(
            model_name="historicaltour",
            name="time_approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Arbeitszeit übernommen von",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="time_approval_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Begründung Arbeitszeit"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="time_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Arbeitszeit übernommen am"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="time_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Arbeitszeit übernommen von",
            ),
        ),
    ]
