# Generated by Django 5.2.17 on 2026-09-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_historicaltour_time_approval_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tour",
            options={
                "ordering": ["date", "employee__short_name"],
                "permissions": [
                    ("confirm_tour", "Fahrplan bestätigen"),
                    ("view_own_tours", "Eigenen Tagesplan sehen"),
                    ("view_reports", "Auswertungen und Zeiten je Ableser sehen"),
                    ("view_week_hours", "Wochenstunden je Mitarbeiter sehen"),
                ],
                "verbose_name": "Fahrplan",
                "verbose_name_plural": "Fahrpläne",
            },
        ),
        migrations.AddField(
            model_name="historicaltour",
            name="split_work",
            field=models.BooleanField(
                default=True, verbose_name="Arbeitszeit auf das Team aufteilen"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="split_work",
            field=models.BooleanField(
                default=True, verbose_name="Arbeitszeit auf das Team aufteilen"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="team",
            field=models.ManyToManyField(
                blank=True,
                related_name="team_tours",
                to="planning.employee",
                verbose_name="im Team mit",
            ),
        ),
    ]
