# Generated by Django 5.2.17 on 2026-09-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0004_alter_tour_options_historicaltour_split_work_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltour",
            name="time_approval_note",
        ),
        migrations.RemoveField(
            model_name="historicaltour",
            name="time_approved_at",
        ),
        migrations.RemoveField(
            model_name="historicaltour",
            name="time_approved_by",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="time_approval_note",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="time_approved_at",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="time_approved_by",
        ),
    ]
