# Generated by Django 5.2.17 on 2026-09-29 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_alter_building_geocode_status_and_more"),
        ("planning", "0005_remove_historicaltour_time_approval_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tourstop",
            name="stop_kind_matches_reference",
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="help_tour",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="planning.tour",
                verbose_name="hilft im Plan",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="help_tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="help_stops",
                to="planning.tour",
                verbose_name="hilft im Plan",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltourstop",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="tourstop",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AddConstraint(
            model_name="tourstop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building__isnull", False),
                        ("installation_order__isnull", True),
                        ("kind", "reading"),
                    ),
                    models.Q(
                        ("installation_order__isnull", False), ("kind", "installation")
                    ),
                    models.Q(("building__isnull", False), ("kind", "help")),
                    models.Q(("installation_order__isnull", False), ("kind", "help")),
                    _connector="OR",
                ),
                name="stop_kind_matches_reference",
            ),
        ),
    ]
