# Generated by Django 5.2.17 on 2026-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0006_remove_tourstop_stop_kind_matches_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_for",
            field=models.CharField(
                blank=True,
                help_text="z. B. „Dienstag, 03.11.2026, zwischen 09:00 und 11:00 Uhr“",
                max_length=120,
                verbose_name="Aushang für",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_printed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aushang gedruckt am"
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_for",
            field=models.CharField(
                blank=True,
                help_text="z. B. „Dienstag, 03.11.2026, zwischen 09:00 und 11:00 Uhr“",
                max_length=120,
                verbose_name="Aushang für",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_printed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Aushang gedruckt am"
            ),
        ),
    ]
