# Generated by Django 5.2.17 on 2026-09-29 10:11

from django.db import migrations, models


def printed_are_wanted(apps, schema_editor):
    """Notices printed before the switch existed stay switched on."""
    apps.get_model("planning", "TourStop").objects.exclude(notice_printed_at=None).update(notice_wanted=True)


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0007_historicaltourstop_notice_for_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_wanted",
            field=models.BooleanField(default=False, verbose_name="Aushang nötig"),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_wanted",
            field=models.BooleanField(default=False, verbose_name="Aushang nötig"),
        ),
        migrations.RunPython(printed_are_wanted, migrations.RunPython.noop),
    ]
