# Generated by Django 5.2.17 on 2026-09-29 13:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_prices"),
        ("planning", "0009_notice_printed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltourstop",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complete", "fertig (100 %)"),
                    ("partial", "teilweise erledigt"),
                    ("absent", "nicht erledigt"),
                ],
                max_length=20,
                verbose_name="Ergebnis",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complete", "fertig (100 %)"),
                    ("partial", "teilweise erledigt"),
                    ("absent", "nicht erledigt"),
                ],
                max_length=20,
                verbose_name="Ergebnis",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalVisit",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reading", "Ablesung"),
                            ("installation", "Montage"),
                            ("help", "Hilfe bei Objekt"),
                        ],
                        default="reading",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Tag")),
                (
                    "people",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="wer war da"
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Termin Nr."
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("complete", "fertig (100 %)"),
                            ("partial", "teilweise erledigt"),
                            ("absent", "nicht erledigt"),
                        ],
                        max_length=20,
                        verbose_name="Ergebnis",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=20, verbose_name="Grund"),
                ),
                (
                    "todo",
                    models.TextField(blank=True, verbose_name="Was ist noch zu tun?"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz vor Ort")),
                (
                    "reported_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="gemeldet am"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="abgeschlossen am"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="abgeschlossen von",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="buildings.installationorder",
                        verbose_name="Montageauftrag",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gemeldet von",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planning.tourstop",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planning.tour",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Termin-Ergebnis",
                "verbose_name_plural": "historical Termin-Ergebnisse",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reading", "Ablesung"),
                            ("installation", "Montage"),
                            ("help", "Hilfe bei Objekt"),
                        ],
                        default="reading",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Tag")),
                (
                    "people",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="wer war da"
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Termin Nr."
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("complete", "fertig (100 %)"),
                            ("partial", "teilweise erledigt"),
                            ("absent", "nicht erledigt"),
                        ],
                        max_length=20,
                        verbose_name="Ergebnis",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=20, verbose_name="Grund"),
                ),
                (
                    "todo",
                    models.TextField(blank=True, verbose_name="Was ist noch zu tun?"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz vor Ort")),
                (
                    "reported_at",
                    models.DateTimeField(auto_now=True, verbose_name="gemeldet am"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="abgeschlossen am"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="abgeschlossen von",
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="buildings.installationorder",
                        verbose_name="Montageauftrag",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gemeldet von",
                    ),
                ),
                (
                    "stop",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit",
                        to="planning.tourstop",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="planning.tour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin-Ergebnis",
                "verbose_name_plural": "Termin-Ergebnisse",
                "ordering": ["date", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("building__isnull", False),
                            ("installation_order__isnull", False),
                            _connector="OR",
                        ),
                        name="visit_has_target",
                    )
                ],
            },
        ),
    ]
