# Generated by Django 5.2.17 on 2026-09-30 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0010_visits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visit",
            options={
                "ordering": ["date", "pk"],
                "permissions": [
                    (
                        "process_visit",
                        "Rückmeldungen bearbeiten (geprüft, abschließen, nachtragen)",
                    )
                ],
                "verbose_name": "Termin-Ergebnis",
                "verbose_name_plural": "Termin-Ergebnisse",
            },
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="closed_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Bemerkung Büro"
            ),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="entered_by_office",
            field=models.BooleanField(
                default=False, verbose_name="im Büro nachgetragen"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="closed_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Bemerkung Büro"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="entered_by_office",
            field=models.BooleanField(
                default=False, verbose_name="im Büro nachgetragen"
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisit",
            name="reported_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="gemeldet am"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="reported_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="gemeldet am"
            ),
        ),
    ]
