# Generated by Django 5.2.17 on 2026-10-01 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_prices"),
        ("planning", "0011_office"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tourstop",
            name="stop_kind_matches_reference",
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aushang", "📄 Aushang durch uns"),
                    ("brief", "✉ Brief von uns"),
                    ("mail_hv", "📧 Mail an Hausverwaltung"),
                    ("aushang_hv", "🏢 Aushang durch Hausverwaltung"),
                    ("telefon", "📞 telefonisch mit Mieter"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=20,
                verbose_name="Ankündigung",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_from",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Zeitfenster von (von Hand)"
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_scope",
            field=models.CharField(
                choices=[
                    ("haus", "ganzes Haus"),
                    ("wohnungen", "nur bestimmte Wohnungen"),
                ],
                default="haus",
                max_length=10,
                verbose_name="Ankündigung für",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="aufgehängt / Brief verschickt / Mail an HV verschickt …",
                null=True,
                verbose_name="angekündigt am",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_sent_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="angekündigt von",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_to",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Zeitfenster bis (von Hand)"
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_units",
            field=models.CharField(
                blank=True,
                help_text="z. B. „Whg 3 (Müller), Whg 7“ – bei Nachablesung / Nachmontage",
                max_length=300,
                verbose_name="nur Wohnungen",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aushang", "📄 Aushang durch uns"),
                    ("brief", "✉ Brief von uns"),
                    ("mail_hv", "📧 Mail an Hausverwaltung"),
                    ("aushang_hv", "🏢 Aushang durch Hausverwaltung"),
                    ("telefon", "📞 telefonisch mit Mieter"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=20,
                verbose_name="Ankündigung",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_from",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Zeitfenster von (von Hand)"
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_scope",
            field=models.CharField(
                choices=[
                    ("haus", "ganzes Haus"),
                    ("wohnungen", "nur bestimmte Wohnungen"),
                ],
                default="haus",
                max_length=10,
                verbose_name="Ankündigung für",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="aufgehängt / Brief verschickt / Mail an HV verschickt …",
                null=True,
                verbose_name="angekündigt am",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="angekündigt von",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_to",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Zeitfenster bis (von Hand)"
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_units",
            field=models.CharField(
                blank=True,
                help_text="z. B. „Whg 3 (Müller), Whg 7“ – bei Nachablesung / Nachmontage",
                max_length=300,
                verbose_name="nur Wohnungen",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltourstop",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                    ("notice", "Aushang aufhängen"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisit",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                    ("notice", "Aushang aufhängen"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="tourstop",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                    ("notice", "Aushang aufhängen"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                    ("notice", "Aushang aufhängen"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AddConstraint(
            model_name="tourstop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building__isnull", False),
                        ("installation_order__isnull", True),
                        ("kind", "reading"),
                    ),
                    models.Q(
                        ("installation_order__isnull", False), ("kind", "installation")
                    ),
                    models.Q(("building__isnull", False), ("kind", "help")),
                    models.Q(("installation_order__isnull", False), ("kind", "help")),
                    models.Q(("building__isnull", False), ("kind", "notice")),
                    models.Q(("installation_order__isnull", False), ("kind", "notice")),
                    _connector="OR",
                ),
                name="stop_kind_matches_reference",
            ),
        ),
    ]
