# Generated by Django 5.2.17 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0012_notice_trips"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="can_notice",
            field=models.BooleanField(
                default=False,
                help_text="fährt Aushänge aus (📄 Aushang-Fahrten)",
                verbose_name="Aushänge",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployee",
            name="can_notice",
            field=models.BooleanField(
                default=False,
                help_text="fährt Aushänge aus (📄 Aushang-Fahrten)",
                verbose_name="Aushänge",
            ),
        ),
    ]
