# Generated by Django 5.2.17 on 2026-10-01 11:26

from django.conf import settings
from django.db import migrations, models


def drop_notice_trips(apps, schema_editor):
    """The 📄 Aushang-Fahrt stops are gone (the Aushang route is a printed list now)."""
    TourStop = apps.get_model("planning", "TourStop")
    Tour = apps.get_model("planning", "Tour")
    tours = set(TourStop.objects.filter(kind="notice").values_list("tour_id", flat=True))
    TourStop.objects.filter(kind="notice").delete()
    Tour.objects.filter(pk__in=tours, stops__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_prices"),
        ("planning", "0013_employee_can_notice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_notice_trips, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="tourstop",
            name="stop_kind_matches_reference",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="can_notice",
        ),
        migrations.RemoveField(
            model_name="historicalemployee",
            name="can_notice",
        ),
        migrations.RemoveField(
            model_name="historicaltourstop",
            name="notice_channel",
        ),
        migrations.RemoveField(
            model_name="historicaltourstop",
            name="notice_sent_at",
        ),
        migrations.RemoveField(
            model_name="historicaltourstop",
            name="notice_sent_by",
        ),
        migrations.RemoveField(
            model_name="tourstop",
            name="notice_channel",
        ),
        migrations.RemoveField(
            model_name="tourstop",
            name="notice_sent_at",
        ),
        migrations.RemoveField(
            model_name="tourstop",
            name="notice_sent_by",
        ),
        migrations.AlterField(
            model_name="historicaltourstop",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltourstop",
            name="notice_scope",
            field=models.CharField(
                choices=[
                    ("haus", "📄 Aushang ans ganze Haus"),
                    ("wohnungen", "✉ Briefe an einzelne Wohnungen"),
                ],
                default="haus",
                max_length=10,
                verbose_name="Aushang / Briefe",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltourstop",
            name="notice_units",
            field=models.CharField(
                blank=True,
                help_text="z. B. „Whg 3 (Müller), Whg 7“ – je Wohnung ein Brief",
                max_length=300,
                verbose_name="Wohnungen",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisit",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="tourstop",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AlterField(
            model_name="tourstop",
            name="notice_scope",
            field=models.CharField(
                choices=[
                    ("haus", "📄 Aushang ans ganze Haus"),
                    ("wohnungen", "✉ Briefe an einzelne Wohnungen"),
                ],
                default="haus",
                max_length=10,
                verbose_name="Aushang / Briefe",
            ),
        ),
        migrations.AlterField(
            model_name="tourstop",
            name="notice_units",
            field=models.CharField(
                blank=True,
                help_text="z. B. „Whg 3 (Müller), Whg 7“ – je Wohnung ein Brief",
                max_length=300,
                verbose_name="Wohnungen",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reading", "Ablesung"),
                    ("installation", "Montage"),
                    ("help", "Hilfe bei Objekt"),
                ],
                default="reading",
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.AddConstraint(
            model_name="tourstop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building__isnull", False),
                        ("installation_order__isnull", True),
                        ("kind", "reading"),
                    ),
                    models.Q(
                        ("installation_order__isnull", False), ("kind", "installation")
                    ),
                    models.Q(("building__isnull", False), ("kind", "help")),
                    models.Q(("installation_order__isnull", False), ("kind", "help")),
                    _connector="OR",
                ),
                name="stop_kind_matches_reference",
            ),
        ),
    ]
