# Generated by Django 5.2.17 on 2026-10-01 14:10

from django.db import migrations, models


def decided_before(apps, schema_editor):
    """Aushänge already switched on (or printed) count as decided: Aushang / Briefe."""
    TourStop = apps.get_model("planning", "TourStop")
    wanted = TourStop.objects.filter(notice_wanted=True) | TourStop.objects.filter(notice_printed_at__isnull=False)
    wanted.filter(notice_scope="wohnungen").update(notice_choice="briefe")
    wanted.exclude(notice_scope="wohnungen").update(notice_choice="aushang")


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0014_aushang_simple"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltourstop",
            name="access_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alle", "alle Wohnungen"),
                    ("einige", "nur diese Wohnungen"),
                    ("keine", "nicht in die Wohnungen"),
                ],
                max_length=10,
                verbose_name="Zugang",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="access_units",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Zugang: Wohnungen"
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="notice_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aushang", "Aushang"),
                    ("briefe", "Briefe"),
                    ("telefon", "telefonisch"),
                    ("mail", "per Mail"),
                    ("keine", "keine"),
                ],
                max_length=10,
                verbose_name="Ankündigung",
            ),
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="visit_mode",
            field=models.CharField(
                blank=True,
                choices=[("aussen", "von außen, ohne Termin")],
                max_length=10,
                verbose_name="Besuch",
            ),
        ),
        migrations.AddField(
            model_name="historicalvisit",
            name="visit_mode",
            field=models.CharField(blank=True, max_length=10, verbose_name="Besuch"),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="access_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alle", "alle Wohnungen"),
                    ("einige", "nur diese Wohnungen"),
                    ("keine", "nicht in die Wohnungen"),
                ],
                max_length=10,
                verbose_name="Zugang",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="access_units",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Zugang: Wohnungen"
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="notice_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aushang", "Aushang"),
                    ("briefe", "Briefe"),
                    ("telefon", "telefonisch"),
                    ("mail", "per Mail"),
                    ("keine", "keine"),
                ],
                max_length=10,
                verbose_name="Ankündigung",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="visit_mode",
            field=models.CharField(
                blank=True,
                choices=[("aussen", "von außen, ohne Termin")],
                max_length=10,
                verbose_name="Besuch",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="visit_mode",
            field=models.CharField(blank=True, max_length=10, verbose_name="Besuch"),
        ),
        migrations.RunPython(decided_before, migrations.RunPython.noop),
    ]
