# Generated by Django 5.2.17 on 2026-10-01 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0005_readout"),
        ("planning", "0015_readout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterimReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                ("move_date", models.DateField(verbose_name="Nutzerwechsel am")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("mail_hv", "Mail der Hausverwaltung"),
                            ("telefon", "Anruf"),
                            ("brief", "Brief"),
                            ("sonstiges", "sonstiges"),
                        ],
                        default="mail_hv",
                        max_length=12,
                        verbose_name="gemeldet per",
                    ),
                ),
                (
                    "reported_on",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="gemeldet am",
                    ),
                ),
                ("flats", models.JSONField(default=list, verbose_name="Wohnungen")),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="storniert am"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interim_readings",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="angelegt von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zwischenablesung",
                "verbose_name_plural": "Zwischenablesungen",
                "ordering": ["move_date", "pk"],
            },
        ),
        migrations.AddField(
            model_name="historicaltourstop",
            name="interim",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="planning.interimreading",
                verbose_name="Zwischenablesung",
            ),
        ),
        migrations.AddField(
            model_name="tourstop",
            name="interim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stops",
                to="planning.interimreading",
                verbose_name="Zwischenablesung",
            ),
        ),
    ]
