# Generated by Django 5.2.17 on 2026-09-26 17:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostDocumentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "received_on",
                    models.DateField(verbose_name="Unterlagen erhalten am"),
                ),
                ("deadline_start", models.DateField(verbose_name="Frist läuft ab")),
                (
                    "reset_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("status", "Statuswechsel"),
                            ("appointment", "neuer Termin"),
                        ],
                        max_length=20,
                        verbose_name="Frist neu gestartet wegen",
                    ),
                ),
                (
                    "last_seen_status",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Status bei letzter Prüfung",
                    ),
                ),
                (
                    "last_seen_planned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termin bei letzter Prüfung"
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_documents",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="eingetragen von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unterlagen-Eingang",
                "verbose_name_plural": "Unterlagen-Eingänge",
            },
        ),
        migrations.CreateModel(
            name="CoverSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Quelldatei"
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Seite"
                    ),
                ),
                (
                    "source_label",
                    models.CharField(blank=True, max_length=200, verbose_name="Quelle"),
                ),
                (
                    "owner_text",
                    models.TextField(
                        blank=True, verbose_name="Eigentümer laut Deckblatt"
                    ),
                ),
                (
                    "property_manager_text",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Hausverwaltung laut Deckblatt",
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_sheet",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deckblatt",
                "verbose_name_plural": "Deckblätter",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCostDocumentReceipt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "received_on",
                    models.DateField(verbose_name="Unterlagen erhalten am"),
                ),
                ("deadline_start", models.DateField(verbose_name="Frist läuft ab")),
                (
                    "reset_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("status", "Statuswechsel"),
                            ("appointment", "neuer Termin"),
                        ],
                        max_length=20,
                        verbose_name="Frist neu gestartet wegen",
                    ),
                ),
                (
                    "last_seen_status",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Status bei letzter Prüfung",
                    ),
                ),
                (
                    "last_seen_planned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termin bei letzter Prüfung"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="eingetragen von",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Unterlagen-Eingang",
                "verbose_name_plural": "historical Unterlagen-Eingänge",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
