# Generated by Django 5.2.17 on 2026-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        default="Ihr Messdienst (bitte in der Verwaltung eintragen)",
                        max_length=200,
                        verbose_name="Firma",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="E-Mail"
                    ),
                ),
                (
                    "office_hours",
                    models.CharField(
                        blank=True,
                        default="Mo–Fr 8:00–16:00 Uhr",
                        max_length=120,
                        verbose_name="Erreichbar",
                    ),
                ),
                (
                    "change_until_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Auf dem Aushang: „Passt der Termin nicht? Bitte bis … anrufen.“",
                        verbose_name="Terminänderung bis … Tage vorher",
                    ),
                ),
                (
                    "extra_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Erscheint unten auf jedem Aushang (z. B. Hinweis zur Heizung).",
                        verbose_name="Zusätzlicher Hinweis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aushang-Einstellungen",
                "verbose_name_plural": "Aushang-Einstellungen",
            },
        ),
    ]
