# Generated by Django 5.2.17 on 2026-09-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_noticesettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NoticeSettings",
        ),
    ]
