# Generated by Django 5.2.17 on 2026-09-26 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0002_initial"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("install_after_reading", "Montage nach der Ablesung"),
                            ("same_day", "Montage und Ablesung am selben Tag"),
                            ("buffer_short", "Montage 1–7 Tage vor der Ablesung"),
                            (
                                "radio_retrofit",
                                "Umrüstung auf Funk bei manueller Ableseart",
                            ),
                            (
                                "same_person",
                                "Monteur = Ableser, Termine ≤ 3 Tage auseinander",
                            ),
                            (
                                "gateway_not_marked",
                                "Gateway-Montage, Liegenschaft nicht als Gateway markiert",
                            ),
                            ("order_without_date", "Auftrag ohne Montagetermin"),
                            (
                                "already_in_other_tour",
                                "Liegenschaft steht schon in einem anderen Plan",
                            ),
                            ("already_has_date", "Liegenschaft hat schon einen Termin"),
                            (
                                "employee_absent",
                                "Mitarbeiter ist an diesem Tag abwesend",
                            ),
                        ],
                        max_length=40,
                        verbose_name="Regel",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("hint", "Hinweis"),
                            ("warning", "Warnung"),
                            ("critical", "kritisch"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Bewertung",
                    ),
                ),
                ("message", models.TextField(verbose_name="Meldung")),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="übernommen am"
                    ),
                ),
                (
                    "acknowledged_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Begründung"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="bewusst übernommen von",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="buildings.building",
                        verbose_name="Liegenschaft",
                    ),
                ),
                (
                    "installation_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="buildings.installationorder",
                        verbose_name="Montageauftrag",
                    ),
                ),
                (
                    "other_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="planning.tourstop",
                        verbose_name="anderer Stopp",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="planning.tourstop",
                        verbose_name="Stopp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konflikt",
                "verbose_name_plural": "Konflikte",
                "ordering": ["-created_at"],
                "permissions": [
                    ("acknowledge_conflict", "Konflikt bewusst übernehmen")
                ],
            },
        ),
    ]
