# Generated by Django 5.2.17 on 2026-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conflicts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conflict",
            name="rule",
            field=models.CharField(
                choices=[
                    ("install_after_reading", "Montage nach der Ablesung"),
                    ("same_day", "Montage und Ablesung am selben Tag"),
                    ("buffer_short", "Montage 1–7 Tage vor der Ablesung"),
                    ("radio_retrofit", "Umrüstung auf Funk bei manueller Ableseart"),
                    ("same_person", "Monteur = Ableser, Termine ≤ 3 Tage auseinander"),
                    (
                        "gateway_not_marked",
                        "Gateway-Montage, Liegenschaft nicht als Gateway markiert",
                    ),
                    ("order_without_date", "Auftrag ohne Montagetermin"),
                    ("no_reading_date", "Montage geplant, aber kein Ablesetag"),
                    (
                        "already_in_other_tour",
                        "Liegenschaft steht schon in einem anderen Plan",
                    ),
                    ("already_has_date", "Liegenschaft hat schon einen Termin"),
                    ("employee_absent", "Mitarbeiter ist an diesem Tag abwesend"),
                ],
                max_length=40,
                verbose_name="Regel",
            ),
        ),
    ]
