# Generated by Django 5.2.17 on 2026-09-26 17:25

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Breitengrad"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "noch nicht gesucht"),
                            ("ok", "gefunden"),
                            ("failed", "nicht gefunden"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Geocoding",
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geocodiert am"
                    ),
                ),
                (
                    "geocoded_address",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="geocodierte Adresse"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("bfw_main", "BFW Main"),
                            ("ceos", "CEOS"),
                            ("miclas", "Miclas"),
                        ],
                        max_length=20,
                        verbose_name="Quellsystem",
                    ),
                ),
                (
                    "file_number",
                    models.CharField(
                        max_length=20, verbose_name="Liegenschafts-Nr. (AZ)"
                    ),
                ),
                (
                    "file_number_core",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=20,
                        verbose_name="AZ-Kern",
                    ),
                ),
                ("stichtag", models.DateField(db_index=True, verbose_name="Stichtag")),
                (
                    "billing_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Abrechnungszeitraum von"
                    ),
                ),
                (
                    "billing_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Abrechnungszeitraum bis"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Region"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "offen"),
                            ("rework", "Nacharbeit"),
                            ("released", "freigegeben"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status geändert am"
                    ),
                ),
                (
                    "proposed_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "offen"),
                            ("rework", "Nacharbeit"),
                            ("released", "freigegeben"),
                        ],
                        max_length=10,
                        verbose_name="vorgeschlagener Status",
                    ),
                ),
                (
                    "proposed_status_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vorgeschlagen am"
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Ableseart",
                    ),
                ),
                (
                    "installation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("radio", "Funkanlage"),
                            ("radio_gateway", "Funkanlage + Gateway"),
                            ("partial_radio", "Teilfunkanlage"),
                            ("sontex_manual", "Sontex 566 + alles andere manuell"),
                            ("manual", "Manuell ablesen"),
                        ],
                        max_length=20,
                        verbose_name="Anlagenstatus",
                    ),
                ),
                (
                    "hkv_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="HKV-Typ"
                    ),
                ),
                (
                    "hkv_family",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="HKV-Familie"
                    ),
                ),
                (
                    "hkv_variant",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="HKV-Variante"
                    ),
                ),
                (
                    "has_gateway",
                    models.BooleanField(
                        default=False, verbose_name="Gateway vorhanden"
                    ),
                ),
                (
                    "apartments",
                    models.PositiveIntegerField(default=0, verbose_name="Wohnungen"),
                ),
                (
                    "hkv_count",
                    models.PositiveIntegerField(default=0, verbose_name="HKV"),
                ),
                (
                    "wmz_count",
                    models.PositiveIntegerField(default=0, verbose_name="WMZ"),
                ),
                (
                    "wwz_count",
                    models.PositiveIntegerField(default=0, verbose_name="WWZ"),
                ),
                (
                    "kwz_count",
                    models.PositiveIntegerField(default=0, verbose_name="KWZ"),
                ),
                (
                    "rwm_count",
                    models.PositiveIntegerField(default=0, verbose_name="RWM Anzahl"),
                ),
                ("sz_count", models.PositiveIntegerField(default=0, verbose_name="SZ")),
                (
                    "hwmz_count",
                    models.PositiveIntegerField(default=0, verbose_name="HWMZ"),
                ),
                (
                    "has_rwm",
                    models.BooleanField(blank=True, null=True, verbose_name="RWM"),
                ),
                (
                    "has_gwz",
                    models.BooleanField(blank=True, null=True, verbose_name="GWZ"),
                ),
                (
                    "has_hwz",
                    models.BooleanField(blank=True, null=True, verbose_name="HWZ"),
                ),
                (
                    "has_wwmz",
                    models.BooleanField(blank=True, null=True, verbose_name="WWMZ"),
                ),
                (
                    "detail_heat",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Details Wärme"
                    ),
                ),
                (
                    "detail_cold_water",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Details KWZ"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, verbose_name="Bemerkung (Quellsystem)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "handwritten_note",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Handschriftlicher Vermerk",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Auftrag (RE-Nr.)"
                    ),
                ),
                (
                    "reading_minutes_calculated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ablesezeit berechnet (min)"
                    ),
                ),
                (
                    "reading_minutes_manual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ablesezeit manuell (min)"
                    ),
                ),
                (
                    "access_apartment",
                    models.BooleanField(
                        default=False, verbose_name="Zugang zur Wohnung nötig"
                    ),
                ),
                (
                    "access_room",
                    models.BooleanField(
                        default=False, verbose_name="Zugang Heiz-/Technikraum nötig"
                    ),
                ),
                (
                    "access_units",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="betroffene Nutzeinheiten",
                    ),
                ),
                (
                    "access_reasons",
                    models.JSONField(blank=True, default=list, verbose_name="Gründe"),
                ),
                (
                    "key_hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis Schlüssel"
                    ),
                ),
                (
                    "announcement_hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis Anmeldung"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Rohdaten"),
                ),
            ],
            options={
                "verbose_name": "Liegenschaft",
                "verbose_name_plural": "Liegenschaften",
                "ordering": ["file_number"],
                "permissions": [
                    ("assign_employee", "Ableser/Monteur zuweisen"),
                    ("set_status_open_rework", "Status offen/Nacharbeit setzen"),
                    ("release_building", "Status freigegeben setzen"),
                    ("propose_status", "Statusänderung vorschlagen"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Kürzel"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Bezeichnung")),
                (
                    "minutes_per_piece",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minuten pro Stück"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerätekategorie",
                "verbose_name_plural": "Gerätekategorien",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBuilding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Breitengrad"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "noch nicht gesucht"),
                            ("ok", "gefunden"),
                            ("failed", "nicht gefunden"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Geocoding",
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geocodiert am"
                    ),
                ),
                (
                    "geocoded_address",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="geocodierte Adresse"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("bfw_main", "BFW Main"),
                            ("ceos", "CEOS"),
                            ("miclas", "Miclas"),
                        ],
                        max_length=20,
                        verbose_name="Quellsystem",
                    ),
                ),
                (
                    "file_number",
                    models.CharField(
                        max_length=20, verbose_name="Liegenschafts-Nr. (AZ)"
                    ),
                ),
                (
                    "file_number_core",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=20,
                        verbose_name="AZ-Kern",
                    ),
                ),
                ("stichtag", models.DateField(db_index=True, verbose_name="Stichtag")),
                (
                    "billing_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Abrechnungszeitraum von"
                    ),
                ),
                (
                    "billing_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Abrechnungszeitraum bis"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="Region"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "offen"),
                            ("rework", "Nacharbeit"),
                            ("released", "freigegeben"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Status geändert am"
                    ),
                ),
                (
                    "proposed_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "offen"),
                            ("rework", "Nacharbeit"),
                            ("released", "freigegeben"),
                        ],
                        max_length=10,
                        verbose_name="vorgeschlagener Status",
                    ),
                ),
                (
                    "proposed_status_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vorgeschlagen am"
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Ableseart",
                    ),
                ),
                (
                    "installation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("radio", "Funkanlage"),
                            ("radio_gateway", "Funkanlage + Gateway"),
                            ("partial_radio", "Teilfunkanlage"),
                            ("sontex_manual", "Sontex 566 + alles andere manuell"),
                            ("manual", "Manuell ablesen"),
                        ],
                        max_length=20,
                        verbose_name="Anlagenstatus",
                    ),
                ),
                (
                    "hkv_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="HKV-Typ"
                    ),
                ),
                (
                    "hkv_family",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="HKV-Familie"
                    ),
                ),
                (
                    "hkv_variant",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="HKV-Variante"
                    ),
                ),
                (
                    "has_gateway",
                    models.BooleanField(
                        default=False, verbose_name="Gateway vorhanden"
                    ),
                ),
                (
                    "apartments",
                    models.PositiveIntegerField(default=0, verbose_name="Wohnungen"),
                ),
                (
                    "hkv_count",
                    models.PositiveIntegerField(default=0, verbose_name="HKV"),
                ),
                (
                    "wmz_count",
                    models.PositiveIntegerField(default=0, verbose_name="WMZ"),
                ),
                (
                    "wwz_count",
                    models.PositiveIntegerField(default=0, verbose_name="WWZ"),
                ),
                (
                    "kwz_count",
                    models.PositiveIntegerField(default=0, verbose_name="KWZ"),
                ),
                (
                    "rwm_count",
                    models.PositiveIntegerField(default=0, verbose_name="RWM Anzahl"),
                ),
                ("sz_count", models.PositiveIntegerField(default=0, verbose_name="SZ")),
                (
                    "hwmz_count",
                    models.PositiveIntegerField(default=0, verbose_name="HWMZ"),
                ),
                (
                    "has_rwm",
                    models.BooleanField(blank=True, null=True, verbose_name="RWM"),
                ),
                (
                    "has_gwz",
                    models.BooleanField(blank=True, null=True, verbose_name="GWZ"),
                ),
                (
                    "has_hwz",
                    models.BooleanField(blank=True, null=True, verbose_name="HWZ"),
                ),
                (
                    "has_wwmz",
                    models.BooleanField(blank=True, null=True, verbose_name="WWMZ"),
                ),
                (
                    "detail_heat",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Details Wärme"
                    ),
                ),
                (
                    "detail_cold_water",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Details KWZ"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, verbose_name="Bemerkung (Quellsystem)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
                (
                    "handwritten_note",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Handschriftlicher Vermerk",
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Auftrag (RE-Nr.)"
                    ),
                ),
                (
                    "reading_minutes_calculated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ablesezeit berechnet (min)"
                    ),
                ),
                (
                    "reading_minutes_manual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ablesezeit manuell (min)"
                    ),
                ),
                (
                    "access_apartment",
                    models.BooleanField(
                        default=False, verbose_name="Zugang zur Wohnung nötig"
                    ),
                ),
                (
                    "access_room",
                    models.BooleanField(
                        default=False, verbose_name="Zugang Heiz-/Technikraum nötig"
                    ),
                ),
                (
                    "access_units",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="betroffene Nutzeinheiten",
                    ),
                ),
                (
                    "access_reasons",
                    models.JSONField(blank=True, default=list, verbose_name="Gründe"),
                ),
                (
                    "key_hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis Schlüssel"
                    ),
                ),
                (
                    "announcement_hint",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hinweis Anmeldung"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liegenschaft",
                "verbose_name_plural": "historical Liegenschaften",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInstallationOrder",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Breitengrad"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "noch nicht gesucht"),
                            ("ok", "gefunden"),
                            ("failed", "nicht gefunden"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Geocoding",
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geocodiert am"
                    ),
                ),
                (
                    "geocoded_address",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="geocodierte Adresse"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("bfw_main", "BFW Main"),
                            ("ceos", "CEOS"),
                            ("miclas", "Miclas"),
                        ],
                        default="miclas",
                        max_length=20,
                        verbose_name="Quellsystem",
                    ),
                ),
                (
                    "re_number",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="RE-Nr."
                    ),
                ),
                (
                    "process_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Vorgang"),
                ),
                (
                    "building_file_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Liegenschafts-Nr. laut Auftrag",
                    ),
                ),
                (
                    "building_file_number_core",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=20,
                        verbose_name="AZ-Kern",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Auftraggeber"
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Auftragsdatum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("planned", "Verplant"),
                            ("work_card", "Arbeitskarte"),
                            ("in_progress", "In Bearbeitung"),
                            ("done", "Erledigt"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prio_1", "Prio 1"),
                            ("prio_2", "Prio 2"),
                            ("prio_3", "Prio 3"),
                            ("with_reading", "Zusammen mit der HA"),
                        ],
                        max_length=20,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[("rent", "Miete"), ("purchase", "Kauf")],
                        max_length=20,
                        verbose_name="Miete/Kauf",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True,
                        choices=[("installation", "Montage"), ("exchange", "Tausch")],
                        max_length=20,
                        verbose_name="Montage/Tausch",
                    ),
                ),
                (
                    "duration_minutes_calculated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Montagezeit berechnet (min)"
                    ),
                ),
                (
                    "duration_minutes_manual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Montagezeit manuell (min)"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Kurzbeschreibung"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Montageauftrag",
                "verbose_name_plural": "historical Montageaufträge",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPropertyManager",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="angelegt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="geändert am",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Name"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Hausverwaltung",
                "verbose_name_plural": "historical Hausverwaltungen",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InstallationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Breitengrad"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Längengrad"),
                ),
                (
                    "geocode_status",
                    models.CharField(
                        choices=[
                            ("pending", "noch nicht gesucht"),
                            ("ok", "gefunden"),
                            ("failed", "nicht gefunden"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Geocoding",
                    ),
                ),
                (
                    "geocoded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geocodiert am"
                    ),
                ),
                (
                    "geocoded_address",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="geocodierte Adresse"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("bfw_main", "BFW Main"),
                            ("ceos", "CEOS"),
                            ("miclas", "Miclas"),
                        ],
                        default="miclas",
                        max_length=20,
                        verbose_name="Quellsystem",
                    ),
                ),
                (
                    "re_number",
                    models.CharField(max_length=20, unique=True, verbose_name="RE-Nr."),
                ),
                (
                    "process_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Vorgang"),
                ),
                (
                    "building_file_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Liegenschafts-Nr. laut Auftrag",
                    ),
                ),
                (
                    "building_file_number_core",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=20,
                        verbose_name="AZ-Kern",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Auftraggeber"
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Auftragsdatum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("planned", "Verplant"),
                            ("work_card", "Arbeitskarte"),
                            ("in_progress", "In Bearbeitung"),
                            ("done", "Erledigt"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prio_1", "Prio 1"),
                            ("prio_2", "Prio 2"),
                            ("prio_3", "Prio 3"),
                            ("with_reading", "Zusammen mit der HA"),
                        ],
                        max_length=20,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[("rent", "Miete"), ("purchase", "Kauf")],
                        max_length=20,
                        verbose_name="Miete/Kauf",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True,
                        choices=[("installation", "Montage"), ("exchange", "Tausch")],
                        max_length=20,
                        verbose_name="Montage/Tausch",
                    ),
                ),
                (
                    "duration_minutes_calculated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Montagezeit berechnet (min)"
                    ),
                ),
                (
                    "duration_minutes_manual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Montagezeit manuell (min)"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Kurzbeschreibung"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Rohdaten"),
                ),
            ],
            options={
                "verbose_name": "Montageauftrag",
                "verbose_name_plural": "Montageaufträge",
                "ordering": ["re_number"],
            },
        ),
        migrations.CreateModel(
            name="InstallationOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_number",
                    models.CharField(max_length=30, verbose_name="Artikel-Nr."),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Bezeichnung"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Menge"),
                ),
            ],
            options={
                "verbose_name": "Auftragsposition",
                "verbose_name_plural": "Auftragspositionen",
            },
        ),
        migrations.CreateModel(
            name="PropertyManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="geändert am"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Hausverwaltung",
                "verbose_name_plural": "Hausverwaltungen",
                "ordering": ["name"],
            },
        ),
    ]
