# Generated by Django 5.2.17 on 2026-09-26 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="assigned_reader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_buildings",
                to="planning.employee",
                verbose_name="Ableser",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="proposed_status_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vorgeschlagen von",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="assigned_reader",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="planning.employee",
                verbose_name="Ableser",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="proposed_status_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="vorgeschlagen von",
            ),
        ),
        migrations.AddField(
            model_name="historicalinstallationorder",
            name="building",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="buildings.building",
                verbose_name="Liegenschaft",
            ),
        ),
        migrations.AddField(
            model_name="historicalinstallationorder",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpropertymanager",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="installationorder",
            name="assigned_installers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_orders",
                to="planning.employee",
                verbose_name="Monteure",
            ),
        ),
        migrations.AddField(
            model_name="installationorder",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installation_orders",
                to="buildings.building",
                verbose_name="Liegenschaft",
            ),
        ),
        migrations.AddField(
            model_name="installationorderitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="buildings.devicecategory",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AddField(
            model_name="installationorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="buildings.installationorder",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="property_manager",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="buildings.propertymanager",
                verbose_name="Hausverwaltung",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="property_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="buildings.propertymanager",
                verbose_name="Hausverwaltung",
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("source_system", "file_number"),
                name="unique_building_per_source",
            ),
        ),
    ]
