# Generated by Django 5.2.17 on 2026-09-29 11:44

from django.db import migrations, models


def default_prices(apps, schema_editor):
    """Categories that exist already get the prices of the prototype."""
    from buildings.rules.material import DEFAULT_PRICES
    for category in apps.get_model("buildings", "DeviceCategory").objects.filter(price=0):
        category.price = DEFAULT_PRICES.get(category.code, 0)
        category.save(update_fields=["price"])


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0003_alter_building_geocode_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Artikel-Nr."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bezeichnung"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Preis pro Stück (€)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikelpreis",
                "verbose_name_plural": "Artikelpreise",
                "ordering": ["article_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="installationorder",
            options={
                "ordering": ["re_number"],
                "permissions": [("view_costs", "Material und Kosten (Budget) sehen")],
                "verbose_name": "Montageauftrag",
                "verbose_name_plural": "Montageaufträge",
            },
        ),
        migrations.AddField(
            model_name="devicecategory",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Preis pro Stück (€)",
            ),
        ),
        migrations.RunPython(default_prices, migrations.RunPython.noop),
    ]
