# Generated by Django 5.2.17 on 2026-10-01 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_prices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="gateway_checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gateway geprüft von",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="gateway_checked_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gateway geprüft am"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="gateway_manual_devices",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Geräte ohne Funk"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="gateway_manual_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "–"),
                    ("angefordert", "angefordert"),
                    ("erhalten", "erhalten"),
                ],
                max_length=12,
                verbose_name="Werte ohne Funk",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="gateway_missing_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="was fehlt (Wohnung / Gerät)"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="gateway_received",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="davon empfangen"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="gateway_total",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Funk-Geräte gesamt"
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_checked_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gateway geprüft von",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_checked_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gateway geprüft am"
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_manual_devices",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Geräte ohne Funk"
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_manual_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "–"),
                    ("angefordert", "angefordert"),
                    ("erhalten", "erhalten"),
                ],
                max_length=12,
                verbose_name="Werte ohne Funk",
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_missing_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="was fehlt (Wohnung / Gerät)"
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_received",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="davon empfangen"
            ),
        ),
        migrations.AddField(
            model_name="historicalbuilding",
            name="gateway_total",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Funk-Geräte gesamt"
            ),
        ),
    ]
